---
title: "Explorative analysis from targets pipeline"
author: "Emma Cartuyvels, Ward Langeraert, Toon Van Daele"
date: "`r Sys.Date()`" 
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
---

In this document we explore the ABV data set, the cube data generated for birds in Flanders and if there is any indication that the occurrences in both datasets show similar trends. We also explore if certain filters can help improve performance of maps and trends based on the cube data when comparing these to the structured ABV data.

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE, comment = "#>")

library(targets)
Sys.setenv(TAR_PROJECT = "exploratory_analysis")

library(ggplot2)
library(ggpubr)
```

```{r}
tar_read(range_comp_0) |>
  ggplot(aes(x = perc_abv_total_abv,
             y = perc_cube_total_cube)) +
  geom_point() +
  stat_cor(mapping = aes(color = NULL),
           label.x.npc = "centre",
           label.y.npc = "bottom",
           method = "pearson") +
  labs(x = "Percentage of ABV squares occupied\nby species in ABV dataset",
       y = "Percentage of ABV squares occupied\nby species in cube dataset")
```

```{r}

```

